extensions:
  health_check: {}
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679
    
receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'node_exporter'
        scrape_interval: 15s
        static_configs:
        - targets: ['localhost:9100']

processors:
  batch:

exporters:
  file:
    path: ./metrics.log

service:
  extensions: [ health_check, pprof, zpages ]
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [file]  ## Need to configure this 


